#!/usr/bin/python
#-*- coding:utf-8 -*-
import os, sys

import subprocess

# kill system service process
filepath = "/var/run/uvc-camera-service.pid"
if os.access(filepath, os.F_OK):
    pidfile = open(filepath)
    pid = pidfile.read()
    pidfile.close()
    print "kill %s" % pid
    try:
        os.kill(int(pid), 15)
        os.remove(filepath)
    except:
        pass

subprocess.call(['/usr/bin/killall', '-9', 'uvc-camera-service'])

subprocess.call(['/bin/rm', '-rf', '/usr/local/src/libguvcview', '/usr/local/lib/dbus-camera-uvc'])

sys.exit(0)
