<?php
// Call NullObjectTest::main() if this source file is executed directly.
if (!defined('PHPUnit_MAIN_METHOD')) {
    define('PHPUnit_MAIN_METHOD', 'SchemaNullObjectTest::main');
}

require_once 'PHPUnit/Framework.php';
require_once realpath(dirname(__FILE__)) . '/../NullObject.php';

/**
 * Test class for Schema.
 * Generated by PHPUnit on 2008-05-14 at 09:40:20.
 */
class SchemaNullObjectTest extends PHPUnit_Framework_TestCase
{
    private $nullobj;

    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main()
    {
        require_once 'PHPUnit/TextUI/TestRunner.php';

        $suite  = new PHPUnit_Framework_TestSuite('SchemaNullObjectTest');
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        $this->nullobj = new NullObject;
    }

    public function testGet() {
        $this->assertTrue( is_object($this->nullobj->abc) );
        $this->assertTrue( is_object($this->nullobj->abc->def) );
        $this->assertTrue( is_object($this->nullobj->abc->def->xyz) );
    }
    
    /**
     To invoke isset with a property of NullObject will be false always.
     @test
     */
    public function test_isset_a_property_of_null_obj() {
        $this->assertFalse( isset($this->nullobj->abc) );
        $this->assertFalse( isset($this->nullobj->abc->def) );
        $this->assertFalse( isset($this->nullobj->abc->def->xyz) );

        $this->assertTrue( empty($this->nullobj->abc) );
        $this->assertTrue( empty($this->nullobj->abc->def) );
        $this->assertTrue( empty($this->nullobj->abc->def->xyz) );
    }
    
    /**
     To invoke isset with a NullObject itself will be true.
     @test 
     */
    public function test_isset_a_null_obj() {
        $this->assertTrue( isset($this->nullobj) );
        $this->assertFalse( empty($this->nullobj) );
    }

    public function testCall() {
        $this->assertTrue( is_object($this->nullobj->abc() ) );
        $this->assertTrue( is_object($this->nullobj->abc()->def() ) );
        $this->assertTrue( is_object($this->nullobj->abc()->def()->xyz() ) );

        $this->assertTrue( is_object($this->nullobj->abc->def() ) );
        $this->assertTrue( is_object($this->nullobj->abc->def->xyz() ) );
    }

}

// Call SchemaNullObjectTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'SchemaNullObjectTest::main') {
    SchemaNullObjectTest::main();
}
?>
