help:
	@echo 
	@echo generate  - generate word tables.
	@echo clean     - clean files.
	@echo
	
generate:
	@sh ./autogen.sh

clean:
	rm -f tbl/1*.tab tbl/2*.tab tbl/3*.tab tbl/4*.tab tbl/5*.tab tbl/6*.tab tbl/7*.tab tbl/8*.tab tbl/9*.tab tbl/0*.tab
	rm -f index2.html

