#! /bin/sh
### BEGIN INIT INFO
# Provides:          mydaemon
# Required-Start:    $syslog $remote_fs
# Required-Stop:     $syslog $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: My Daemon.
# Description:       My Daemon.
### END INIT INFO

DAEMON_NAME=mydaemon
PATH=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=/usr/local/bin/mydaemon
PIDFILE=/var/run/mydaemon.pid

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
  start)
	log_daemon_msg "Starting deferred execution scheduler" "${DAEMON_NAME}"
	start_daemon -p $PIDFILE $DAEMON
	log_end_msg $?
    ;;
  stop)
	log_daemon_msg "Stopping deferred execution scheduler" "${DAEMON_NAME}"
	killproc -p $PIDFILE $DAEMON
	sleep 3
	log_end_msg $?
    ;;
  force-reload|restart)
    $0 stop
    sleep 3
    $0 start
    ;;
  status)
    status_of_proc -p $PIDFILE $DAEMON mgmatchd && exit 0 || exit $?
    ;;
  *)
    echo "Usage: /etc/init.d/${DAEMON_NAME} {start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
