#! /bin/sh
### BEGIN INIT INFO
# Provides:          mydaemon
# Required-Start:    $syslog $remote_fs
# Required-Stop:     $syslog $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: My Daemon.
# Description:       My Daemon.
### END INIT INFO

SERVICE=mydaemon
PATH=/bin:/usr/bin:/sbin:/usr/sbin
PROGRAM=/usr/local/bin/mydaemon
PIDFILE=/var/run/mydaemon.pid

test -x $PROGRAM || exit 0

. /lib/lsb/init-functions

case "$1" in
  start)
	log_daemon_msg "Starting deferred execution scheduler" "$SERVICE"
	start_daemon -p $PIDFILE $PROGRAM
	log_end_msg $?
    ;;
  stop)
	log_daemon_msg "Stopping deferred execution scheduler" "$SERVICE"
	killproc -p $PIDFILE $PROGRAM
    sleep 2
	log_end_msg $?
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  status)
    status_of_proc -p $PIDFILE $PROGRAM $SERVICE && exit 0 || exit $?
    ;;
  *)
    echo "Usage: /etc/init.d/$SERVICE {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
